### ISSUE TITLE
MY 3DS HARDBRICKED ANY HELP

### ISSUE THREAD

**Issue by WERRFG** [WERRFG/MY-3DS-HARDBRICKED-ANY-HELP-#1]
WHEN I BOOT UP IT SAYS PREFETCH ABORT KERNAL; PANIC IS THERE ANY APP THAT MIGHT HELP

**Comment by WERRFG** [comment]
thanks

**Comment by PixelSergey** [comment]
I do not know what you are trying to achieve using this repository (this is NOT what opening an issue on Github means). Nevertheless, try asking on the [Nintendo Homebrew Discord Server](https://discord.gg/C29hYvh) for help.

**Comment by WERRFG** [comment]
im sorted now
